// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20221015163243_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.10");

            modelBuilder.Entity("Application.Common.Model.CartItemDbSet", b =>
                {
                    b.Property<Guid>("CartId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quantity")
                        .HasColumnType("INTEGER");

                    b.HasKey("CartId", "ItemId");

                    b.ToTable("Items");
                });

            modelBuilder.Entity("Application.Common.Model.ItemDbSet", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("ItemId");

                    b.ToTable("CartItems");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            ImageUrl = "https://picsum.photos/200/300",
                            Name = "iPhone 12",
                            Price = 50000m
                        },
                        new
                        {
                            ItemId = 2,
                            ImageUrl = "https://picsum.photos/200/300",
                            Name = "HP Laptop",
                            Price = 50000m
                        },
                        new
                        {
                            ItemId = 3,
                            ImageUrl = "https://picsum.photos/200/300",
                            Name = "Samsung S22 Ultra",
                            Price = 84000m
                        });
                });

            modelBuilder.Entity("CartItemDbSetItemDbSet", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("CartItemCartId")
                        .HasColumnType("TEXT");

                    b.Property<int>("CartItemItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId", "CartItemCartId", "CartItemItemId");

                    b.HasIndex("CartItemCartId", "CartItemItemId");

                    b.ToTable("CartItemDbSetItemDbSet");
                });

            modelBuilder.Entity("CartItemDbSetItemDbSet", b =>
                {
                    b.HasOne("Application.Common.Model.ItemDbSet", null)
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Application.Common.Model.CartItemDbSet", null)
                        .WithMany()
                        .HasForeignKey("CartItemCartId", "CartItemItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
